id: IF680E019
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:48:44+00:00'
last_modified: '2022-06-16T06:08:39.472705+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25392
  title: རི་མོར་བལྟས་ནས་འཚོ་བའི་བརྡ་རྟགས་ངོས་འཛིན་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    FFF5:
      image_group_id: I1KG25394
      title: Volume 1 of ri mor bltas nas 'tsho ba'i brda rtags ngos 'dzin pa/
      total_pages: 66
      order: 1
      base_file: FFF5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
